/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.isnart.api;

import io.swagger.annotations.*;
import it.isnart.model.AreaProdotto;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-12T13:30:44.307Z")

@Api(value = "areeProdotto", description = "the attrattori API")
public interface AreaProdottoApi {

    @ApiOperation(value = "Elenco Aree prodotto", nickname = "findAreeProdotto", notes = "", response = AreaProdotto.class, responseContainer = "List", tags={ "Area Prodotto", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = AreaProdotto.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Area prodotto non trovata") })
    @RequestMapping(value = "/areaProdotto/elenco",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<AreaProdotto>> findAreaProdotto();


}
