/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.isnart.api;

import io.swagger.annotations.*;
import it.isnart.model.Attrattori;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-12T13:30:44.307Z")

@Api(value = "attrattori", description = "the attrattori API")
public interface AttrattoriApi {

    @ApiOperation(value = "Elenco attrattori", nickname = "findAttrattori", notes = "", response = Attrattori.class, responseContainer = "List", tags={ "Attrattori", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Attrattori.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Attrattori non trovati") })
    @RequestMapping(value = "/attrattori/elenco",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Attrattori>> findAttrattori();


    @ApiOperation(value = "Visualizza attrattore per ID", nickname = "getAttrattoreById", notes = "Ottiene un singolo attrattore da mostrare", response = Attrattori.class, tags={ "Attrattori", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Attrattori.class),
        @ApiResponse(code = 400, message = "ID non valido"),
        @ApiResponse(code = 404, message = "Comune non trovato") })
    @RequestMapping(value = "/attrattori/visualizza/{attrattoriId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Attrattori> getAttrattoreById(@ApiParam(value = "ID del attrattore da restituire",required=true) @PathVariable("attrattoriId") Long attrattoriId);

}
