/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.isnart.api;

import io.swagger.annotations.*;
import it.isnart.model.Comuni;
import it.isnart.model.ViewComuni;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-12T13:30:44.307Z")

@Api(value = "comuni", description = "the comuni API")
public interface ComuniApi {

    @ApiOperation(value = "Elenco comuni", nickname = "findComuni", notes = "", response = Comuni.class, responseContainer = "List", tags={ "Comuni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Comuni.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Comini non trovati") })
    @RequestMapping(value = "/comuni/elenco",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ViewComuni>> findComuni();


    @ApiOperation(value = "Visualizza comune per ID", nickname = "getComuneById", notes = "Ottiene un singolo comune da mostrare", response = Comuni.class, tags={ "Comuni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Comuni.class),
        @ApiResponse(code = 400, message = "ID non valido"),
        @ApiResponse(code = 404, message = "Comune non trovato") })
    @RequestMapping(value = "/comuni/visualizza/{comuneId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Comuni> getComuneById(@ApiParam(value = "ID del comune da restituire",required=true) @PathVariable("comuneId") Long comuneId);

}
