/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.isnart.api;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import it.isnart.model.RegistroImprese2018;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-12T13:30:44.307Z")

@Api(value = "RegistroImprese2018", description = "the regioni API")
public interface RegistroImprese2018Api {

    @ApiOperation(value = "Elenco RegistroImprese2018", nickname = "findRegistroImprese2018", notes = "", response = RegistroImprese2018.class, responseContainer = "List", tags={ "RegistroImprese2018", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = RegistroImprese2018.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "RegistroImprese2018 non trovate") })
    @RequestMapping(value = "/registro/elenco/{idComune}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<RegistroImprese2018>> findRegistroImprese2018(@ApiParam(value = "ID dei comuni da restituire",required=true) @PathVariable("idComune") List <Long> idComune);


}
