/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.isnart.api;

import io.swagger.annotations.*;
import it.isnart.model.Regioni;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-12T13:30:44.307Z")

@Api(value = "regioni", description = "the regioni API")
public interface RegioniApi {

    @ApiOperation(value = "Elenco regioni", nickname = "findRegioni", notes = "", response = Regioni.class, responseContainer = "List", tags={ "Regioni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Regioni.class, responseContainer = "List"),
        @ApiResponse(code = 404, message = "Regioni non trovate") })
    @RequestMapping(value = "/regioni/elenco",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Regioni>> findRegioni();


    @ApiOperation(value = "Visualizza regione per ID", nickname = "getRegioneById", notes = "Ottiene una singola regione da mostrare", response = Regioni.class, tags={ "Regioni", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "operazione completata con successo", response = Regioni.class),
        @ApiResponse(code = 400, message = "ID non valido"),
        @ApiResponse(code = 404, message = "Regione non trovata") })
    @RequestMapping(value = "/regioni/visualizza/{regioneId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Regioni> getRegioneById(@ApiParam(value = "ID della regione da restituire",required=true) @PathVariable("regioneId") Long regioneId);

}
